# .sqa/config.yml - jenkins-pipeline-library configuration file
config:
  project_repos:
    saps-scheduler:
      repo: 'https://github.com/EOSC-synergy/saps-scheduler'
      branch: develop

sqa_criteria:
   qc_style:
     repos:
       saps-scheduler:
         container: scheduler-testing
         commands:
           - mvn -f /saps-scheduler-repo/pom.xml checkstyle:checkstyle
   qc_coverage:
     repos:
       saps-scheduler:
         container: scheduler-testing
         commands:
           - mvn -f /saps-scheduler-repo/pom.xml -B -DskipTests clean package
           - mvn -f /saps-scheduler-repo/pom.xml test
